"""LightDM greeter configuration (§8 lock — silent greeter setup).

Writes /etc/lightdm/lightdm-gtk-greeter.conf via pkexec so the login
screen mirrors the active preset: PadOS theme, Carbon icons, IBM Plex
Sans, standard wallpaper, default-preset accent color.

Called from `apply_preset` (mackes.presets) after the appearance section
runs. Idempotent: re-running with the same preset produces no diff.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Optional

from mackes.logging import log_action

GREETER_CONF = Path("/etc/lightdm/lightdm-gtk-greeter.conf")
STANDARD_WALLPAPER = Path("/usr/share/mackes-shell/branding/standard-wallpaper.png")
# Accent-per-preset, mirrored to greeter via the gtk-theme + a small CSS overlay
GREETER_DROPIN = Path("/etc/lightdm/lightdm.conf.d/50-mackes.conf")


def _have(cmd: str) -> bool:
    return shutil.which(cmd) is not None


def _pkexec_write(path: Path, contents: str) -> tuple[int, str]:
    """Use pkexec to write a file as root. Returns (rc, stderr)."""
    if _have("pkexec"):
        prefix = ["pkexec"]
    elif _have("sudo"):
        prefix = ["sudo"]
    else:
        return 127, "neither pkexec nor sudo available"
    cmd = prefix + ["tee", str(path)]
    try:
        proc = subprocess.run(cmd, input=contents, text=True,
                              capture_output=True, timeout=10)
    except (OSError, subprocess.TimeoutExpired) as e:
        return 1, str(e)
    return proc.returncode, proc.stderr or ""


def _pkexec_mkdir(path: Path) -> tuple[int, str]:
    if _have("pkexec"):
        prefix = ["pkexec"]
    elif _have("sudo"):
        prefix = ["sudo"]
    else:
        return 127, "neither pkexec nor sudo available"
    cmd = prefix + ["mkdir", "-p", str(path)]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=5)
    except (OSError, subprocess.TimeoutExpired) as e:
        return 1, str(e)
    return proc.returncode, proc.stderr or ""


def configure_greeter(
    *,
    gtk_theme: str = "PadOS",
    icon_theme: str = "Carbon",
    font_name: str = "IBM Plex Sans 11",
    wallpaper: Optional[Path] = None,
    accent_color: str = "#fa4d56",
) -> list[str]:
    """Write the LightDM greeter config. Returns action log."""
    actions: list[str] = []
    wp = wallpaper or STANDARD_WALLPAPER
    conf = f"""# Generated by Mackes Shell (mackes.lightdm.configure_greeter)
[greeter]
background = {wp}
theme-name = {gtk_theme}
icon-theme-name = {icon_theme}
font-name = {font_name}
xft-antialias = true
xft-hintstyle = hintslight
xft-rgba = rgb
cursor-theme-name = Adwaita
cursor-theme-size = 24
indicators = ~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
clock-format = %a %b %d, %H:%M
position = 50%,center 50%,center
default-user-image = #avatar-default
panel-position = bottom
"""
    rc, err = _pkexec_write(GREETER_CONF, conf)
    if rc == 0:
        actions.append(f"wrote {GREETER_CONF}")
    else:
        actions.append(f"could not write {GREETER_CONF}: {err.strip()}")

    # Drop-in: ensure lightdm-gtk-greeter is the selected greeter
    dropin = "[Seat:*]\ngreeter-session=lightdm-gtk-greeter\n"
    rc2, err2 = _pkexec_mkdir(GREETER_DROPIN.parent)
    if rc2 == 0:
        rc3, err3 = _pkexec_write(GREETER_DROPIN, dropin)
        if rc3 == 0:
            actions.append(f"wrote {GREETER_DROPIN}")
        else:
            actions.append(f"could not write {GREETER_DROPIN}: {err3.strip()}")
    else:
        actions.append(f"could not create {GREETER_DROPIN.parent}: {err2.strip()}")

    for line in actions:
        log_action(line)
    return actions


# Accent color → choose-from-preset helper
ACCENT_BY_PRESET = {
    "hashbang": "#fa4d56",
    "mackes":   "#d4a060",
    "daylight": "#f1c21b",
    "vanilla":  "#0f62fe",
    "node":     "#fa4d56",   # node is headless; accent unused
}


def configure_from_preset(preset_name: str, *, wallpaper: Optional[Path] = None) -> list[str]:
    """Convenience wrapper used by presets.apply_appearance."""
    accent = ACCENT_BY_PRESET.get(preset_name, "#fa4d56")
    return configure_greeter(accent_color=accent, wallpaper=wallpaper)


__all__ = [
    "GREETER_CONF", "GREETER_DROPIN", "STANDARD_WALLPAPER",
    "configure_greeter", "configure_from_preset", "ACCENT_BY_PRESET",
]
